# Generated by Django 3.2.4 on 2021-06-11 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassesModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='students.basemodel')),
                ('class_name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
            ],
            bases=('students.basemodel',),
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='students.basemodel')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('date_of_birth', models.IntegerField()),
                ('student_image', models.FileField(upload_to='student_image/')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_class', to='students.classesmodel')),
            ],
            bases=('students.basemodel',),
        ),
    ]
